repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.8.0
      hooks:
        - id: isort
          args: ["--profile", "black"]
    - repo: https://github.com/psf/black
      rev: 21.4b0
      hooks:
        - id: black
          args: [ solutions ]
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint
          args:
            [
            "--rcfile=.pylintrc",
            ]
          language: system
          types: [python]